import type { IDocument } from '@/interfaces/entities';

const userId = '<my user id>';

export const dummyData: IDocument[] = [
  {
    id: '123',
    userId: userId,
    name: 'Photos',
    path: '/Home',
    pathIds: '/0',
    type: 'FOLDER',
    contentType: '',
    downloadUrl: '',
    extension: '',
    capacity: {
      size: '7 Mb',
      length: 3,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'abc',
    userId: userId,
    name: 'Music',
    path: '/Home',
    pathIds: '/0',
    type: 'FOLDER',
    contentType: '',
    downloadUrl: '',
    extension: '',
    capacity: {
      size: '3 Mb',
      length: 2,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'jkl',
    userId: userId,
    name: 'Elephant',
    path: '/Home',
    pathIds: '/0',
    type: 'FILE',
    contentType: 'image/png',
    downloadUrl: 'https://www.referenseo.com/wp-content/uploads/2019/03/image-attractive-960x540.jpg',
    extension: '.png',
    capacity: {
      size: '15 Mb',
      length: null,
    },
    createdAt: new Date().toDateString(),
  },

  // Nested FILES AND FOLDERS UNDER PHOTOS DIR
  {
    id: 'wxy',
    userId: userId,
    name: 'test-folder',
    path: '/Home/Photos',
    pathIds: '/0/123', // 123 is id of Photos folder
    type: 'FOLDER',
    contentType: '',
    downloadUrl: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
    extension: '',
    capacity: {
      size: '0 Mb',
      length: 0,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'xyz',
    userId: userId,
    name: 'photography and some other long name',
    path: '/Home/Photos',
    pathIds: '/0/123', // 123 is id of Photos folder
    type: 'FILE',
    contentType: 'image/png',
    downloadUrl: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
    extension: '.png',
    capacity: {
      size: '5 Mb',
      length: null,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'nmo',
    userId: userId,
    name: 'Camera',
    path: '/Home/Photos',
    pathIds: '/0/123',
    type: 'FILE',
    contentType: 'image/png',
    downloadUrl: 'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    extension: '.png',
    capacity: {
      size: '2 Mb',
      length: null,
    },
    createdAt: new Date().toDateString(),
  },

  // NESTED FILES AND FOLDERS UNDER MUSIC DIR
  {
    id: 'stu',
    userId: userId,
    name: 'Test Folder',
    path: '/Home/Music',
    pathIds: '/0/abc',
    type: 'FOLDER',
    contentType: '',
    downloadUrl: 'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    extension: '',
    capacity: {
      size: '1 Mb',
      length: 2,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'pqr',
    userId: userId,
    name: 'Camera',
    path: '/Home/Music',
    pathIds: '/0/abc',
    type: 'FILE',
    contentType: 'image/png',
    downloadUrl: 'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    extension: '.png',
    capacity: {
      size: '2 Mb',
      length: null,
    },
    createdAt: new Date().toDateString(),
  },
  // NESTED FILES AND FOLDERS UNDER MUSIC/TEST+FOLDER/ DIR
  {
    id: 'stu',
    userId: userId,
    name: 'my Folder',
    path: '/Home/Music/Test+Folder',
    pathIds: '/0/abc/stu',
    type: 'FOLDER',
    contentType: '',
    downloadUrl: 'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    extension: '',
    capacity: {
      size: '0 Mb',
      length: 0,
    },
    createdAt: new Date().toDateString(),
  },
  {
    id: 'pqr',
    userId: userId,
    name: 'Camera',
    path: '/Home/Music/Test+Folder',
    pathIds: '/0/abc/stu',
    type: 'FILE',
    contentType: 'image/png',
    downloadUrl: 'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    extension: '.png',
    capacity: {
      size: '1 Mb',
      length: null,
    },
    createdAt: new Date().toDateString(),
  },
];
